# environment/environment.yaml

name: aml-DataVis
version: 1
conda_file: conda-environment.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest
description: Environment for data preparation and visualization